GET http://localhost:8000/api/users/current-teacher/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2NDcxNTkwLCJpYXQiOjE3MzYzODUxOTAsImp0aSI6ImYxZWUxOTZkZDJjYjQ4YWViNTFmNDY1MTNiY2Y5OWU3IiwidXNlcl9pZCI6MX0.vuPFf0CfvfKWODNapatrk0jlvcGVia1pAeU08u7-CHc


###



POST http://localhost:8000/api/lessons/
Content-Type: application/json

{
    "lesson_title": "Matemática",
    "lesson_description": "Aula de Matemática",
    "lesson_schedule": "09:23:08",
    "teacher": 2
}


###




GET http://localhost:8000/api/lessons/2


###


DELETE http://localhost:8000/api/lessons/3/


###

PUT http://localhost:8000/api/lessons/2/
Content-Type: application/json

{
    "lesson_title": "Matemática",
    "lesson_description": "Aula de Matemática",
    "lesson_schedule": "2025-01-07T16:02:00-03:00",
    "teacher": 7
}

###


GET http://localhost:8000/api/users/2


###


PUT http://localhost:8000/api/users/2/
Content-Type: application/json

{
  "user_name": "Ricardo Bonaldo",
  "user_email": "ricardo@gmail.com",
  "user_profile_photo": null,
  "is_teacher": true
}


###


GET http://localhost:8000/api/users/dashboard/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2NTIzMzczLCJpYXQiOjE3MzY0MzY5NzMsImp0aSI6Ijc4MjhiMDI0NzEyYzRhOTFiYzBkYTZjY2JhZDUyNzQ1IiwidXNlcl9pZCI6NH0.iTWuQSJ-p5e1BhuFLNwU9Csa0x0zTxJ5D_-bWxooe0Y
