# Generated by Django 5.1.4 on 2025-01-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=100)),
                ('user_email', models.EmailField(default='', max_length=254, unique=True)),
                ('user_profile_photo', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('is_teacher', models.BooleanField(default=False)),
            ],
        ),
    ]
