# Generated by Django 5.1.4 on 2025-01-06 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(default='', max_length=100)),
                ('lesson_description', models.TextField()),
                ('lesson_schedule', models.TimeField()),
                ('students', models.ManyToManyField(related_name='lessons', to='users.user')),
                ('teacher', models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
