# Generated by Django 5.1.4 on 2025-01-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_schedule',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'is_teacher': False}, related_name='lessons', to='users.user'),
        ),
    ]
